### ISSUE TITLE
Implement image viewer

### ISSUE THREAD

**Issue by victorskl** [umccr/data-portal-client#113]
**Context:**

- Some pipeline like [GPL](https://github.com/umccr/gridss-purple-linx-nf) produces series of related plots in PNG format

**Consider:**

- Image viewer dialog for easily skim them through
- Any suitable React component exist

**Actions:**

- Explore

**Comment by ohofmann** [comment]
Oh. Yes please?

**Comment by victorskl** [comment]
Sure! Should be very doable feature 😄
