### ISSUE TITLE
Implement quick file previewer

### ISSUE THREAD

**Issue by victorskl** [umccr/data-portal-client#114]
**Context:**

- Would be good to have a quick previewer dialog for files: `.tsv` `.csv` `.json` `.txt` `.yaml`

**Consider:**

- Idea is just easy quick skim through; say, first few thousand lines or  characters excerpt; so can be truncated
- Any suitable React component exist

**Actions:**

- Explore

**Comment by williamputraintan** [comment]
@victorskl I'll have a go with this one here. Just to clarify, this will be on the action button on the `Subject Data` component?

**Comment by victorskl** [comment]
Ok, let quickly discuss over this today, Will!
