### ISSUE TITLE
Add Generate RNAsum Report button

### ISSUE THREAD

**Issue by victorskl** [umccr/data-portal-client#137]
**Context:**

- Like Generate GPL Report button, add Generate RNAsum Report button
- Requires backend support: https://github.com/umccr/data-portal-apis/issues/481

**FYI:**

- This will go ahead with v1 current production release
- We can/shall backport the feature back to v2 later (no problem!)

**Actions:**

- Add another UI button and flow to LaunchPad wizard

**Comment by victorskl** [comment]
@williamputraintan For TCGA dataset input, it would be good to use a selectable UI component rather than free text data entry. It can be as simple as dropdown.

TCGA datasets are pretty static. We will be using all 3 datasets tables mentioned [here](https://github.com/umccr/RNAsum/blob/master/TCGA_projects_summary.md).

You can statically build this TCGA dataset table as constant. Like [genomes.js](https://github.com/umccr/data-portal-client/blob/dev/src/utils/genomes.js) to start with. Then, we can tinker dynamics lookup from some backend in later iteration. See [#417](https://github.com/umccr/data-portal-apis/issues/417)

Just FYI @reisingerf @skanwal @ohofmann This is the approach we will be taking on Portal UI.

**Comment by victorskl** [comment]
Sorry Will @williamputraintan; I should have state this requirement analysis early. Here is the validation requirement for RNAsum trigger logic at UI.

Around like this:

- In normal mode, RNAsum workflow depends on output of Umccrise and WTS workflows
- If these result are not present in given Subject, then trigger button should straight away responses User with message saying those dependencies output were still missing (like GPL)
- You can infer this from `/subject/<ID>` endpoint i.e. this API has already called & inside `state.subject` of `Subject.js` page — _ditto GPL validation check on bcBio umccrise output for starter_

- For RNAsum case, you will need to check whether
  - at least, one set of umccrise cancer report exist
  - at least, one BAM of WTS exist
  - from Subject’s ICA results set
  
- Also, if there exists RNAsum report in Subject's ICA/GDS result set i.e. `results_gds`, it shouldn't allow trigger...

**Comment by skanwal** [comment]
> Also, if there exists RNAsum report in Subject's ICA/GDS result set i.e. results_gds, it shouldn't allow trigger

Victor, if I understand this point correctly - in case of rerun with updated reference, we'll need to run with the most recent results?

**Comment by victorskl** [comment]
Argh! Yes, you are right, Sehrish. I just strike out that last line requirement.
