### ISSUE TITLE
Implement search and chip filters per data table

### ISSUE THREAD

**Issue by victorskl** [umccr/data-portal-client#157]
**Context:**

- Likewise to v1 data table views, to port back search filter and chip filter buttons functionality

**Actions:**

- To reinstate features

**Comment by victorskl** [comment]
Will; if you are busy at hand & haven't started yet, then no worries. I can take care of this.

**Comment by williamputraintan** [comment]
Yes, I haven't start this yet. Happy if you want to take this.
