### ISSUE TITLE
SearchBox in Subjects Page

### ISSUE THREAD

**Issue by williamputraintan** [umccr/data-portal-client#179]
Context:
The subject list page (`/subject`) does not have search implementation that are able to lookup pinpoint/lookup for a particular subject.

Todo:
Implement

**Comment by victorskl** [comment]
@williamputraintan -- finalising 2.0 release. Do you think, you can push this through or, do want to tackle it in next iteration?

**Comment by williamputraintan** [comment]
Yes, could push this though to the upcoming release.
