### ISSUE TITLE
[Launch Pad v2] Allow user to select T/N libraries and launch WGS T/N workflow

### ISSUE THREAD

**Issue by victorskl** [umccr/data-portal-client#218]
**Context:**

- See story point -- https://trello.com/c/ONt9UvRq/1263-gds-cleanup-add-portal-capability-to-rerun-samples

> We will need the ability to select two libraries identifiers (one tumor, one normal) and request a launch of our T/N WGS workflow on ICA.

**Actions:**

- Implement it

**Comment by williamputraintan** [comment]
Happy to take this ticket.

To start this I suppose we show a list of fastq to be paired and trigger the `data-portal-api-prod-tumor_normal` lambda ([api-doc](https://github.com/umccr/data-portal-apis/blob/dev/docs/pipeline/automation/tumor_normal.md)) from the UI?

@victorskl

**Comment by victorskl** [comment]
Yup. Correct. You on the right track. Here are more pointers for UX/UI flow.

1. We scope this to Subject view to start with. So. Consider you are at a Subject view.
2. A Subject could have multiple libraries. But. We only interest to WGS type. Also. We only interest to --

```
Type: WGS
Phenotype: tumor (or) normal
Workflow: research (or) clinical
```

3. That will give _narrow down_ potential WGS libraries for the UI LaunchPad view to allow user select (dropbox/pick-n-drop/shopping-cart -- need figure some good UI widget here)
4. Therefore, for given Subject, let user select it to
  4a. one library for Tumor
  4b. one library for Normal
5. Once this selection step completed, make Portal API to query related FASTQs to prepare workflow launching payload(*).

---

- (*) Ultimately, we are preparing this Lambda payload. -- 
  - https://github.com/umccr/data-portal-apis/blob/dev/docs/pipeline/automation/tumor_normal_payload.json

- And. Yes. We are doing Option 1. -- 
  - https://github.com/umccr/data-portal-apis/blob/dev/docs/pipeline/automation/tumor_normal.md

**Comment by williamputraintan** [comment]
Thank you for the pointers! Question do we prefer to have an API route or would a direct lambda trigger would be sufficient.

Recalling from RNAsum trigger approach was creating a an API to trigger a ManOps lambda? Ref: [API-#481](https://github.com/umccr/data-portal-apis/issues/481)

**Comment by victorskl** [comment]
Yup. As discussed.

> Question: do we prefer to have an API route or would a direct lambda trigger would be sufficient

We are trying this with Amplify/aws-sdk UI direct call to Lambda

> Recalling from RNAsum trigger approach was creating a an API to trigger a ManOps lambda?

ditto -- https://github.com/umccr/data-portal-apis/issues/555

**Comment by victorskl** [comment]
As discussed; I was a bit miss-leading you on UX flow ☝️  [above comment](https://github.com/umccr/data-portal-client/issues/218#issuecomment-1430624800). My fault. Sorry, Will.

For the first cut; to simplify thing, we should make use of [pairing endpoint](https://github.com/umccr/data-portal-apis/blob/dev/docs/ENDPOINTS.md#pairing-endpoint) by subject.

If we target our audience to end user (i.e. no idea about Metadata relationship such as topup; all possible combination of FASTQ pairs i.e. Library <> Run <> Lane; etc... then it will be more counterproductive to offer selection criteria validation at frontend.

So, let us start with safer approach by utilising pairing endpoint. Then, we shall expand the use case from there in future iteration.

**Comment by victorskl** [comment]
These are few cases that you can use it for dev/testing purpose.

```
curl -s -X POST -d '["SBJ02863"]' -H "Content-Type: application/json" -H "Authorization: Bearer $PORTAL_TOKEN" "https://api.portal.prod.umccr.org/pairing/by_subjects" | jq

curl -s -X POST -d '["SBJ02899"]' -H "Content-Type: application/json" -H "Authorization: Bearer $PORTAL_TOKEN" "https://api.portal.prod.umccr.org/pairing/by_subjects" | jq

curl -s -X POST -d '["SBJ02686"]' -H "Content-Type: application/json" -H "Authorization: Bearer $PORTAL_TOKEN" "https://api.portal.prod.umccr.org/pairing/by_subjects" | jq

curl -s -X POST -d '["SBJ02096"]' -H "Content-Type: application/json" -H "Authorization: Bearer $PORTAL_TOKEN" "https://api.portal.prod.umccr.org/pairing/by_subjects" | jq
```
