### ISSUE TITLE
[Launch Pad v2] RNAsum trigger refactor

### ISSUE THREAD

**Issue by williamputraintan** [umccr/data-portal-client#232]
Context:

Current RNAsum launch workflow is triggering lambda using `manops` api from the backend. The `manops` route will be deprecated and now preferred to trigger the lambda straight from the FE.

To do:
Refactor RNAsum (`manops`) api call to trigger data portal `rnasum` lambda.

**Comment by victorskl** [comment]
ditto [comment](https://github.com/umccr/data-portal-apis/issues/555#issuecomment-1441350385)
