### ISSUE TITLE
[Launch Pad v2] GPL trigger refactor

### ISSUE THREAD

**Issue by victorskl** [umccr/data-portal-client#235]
**Context:**

- Now that we are switching to _direct call to Lambda_ pattern; consider v2 Launch Pad for GPL to use Lambda directly. Instead of Lambda Function URL.
- https://github.com/umccr/gridss-purple-linx-nf/tree/main/deployment#usage

**Caveats:**

- Also consider for v1

**Actions:**

- Analyse the refactor impact
- Implement it, if there possible

**Comment by victorskl** [comment]
@williamputraintan Please see if this is possible too 😬 No stress otherwise

**Comment by williamputraintan** [comment]
Sure!
