### ISSUE TITLE
Add .gvcf in the Analysis Results tables

### ISSUE THREAD

**Issue by raylrui** [umccr/data-portal-client#340]
As required, we may need to add .gvcf back in the UI Analysis Results tables

![image](https://github.com/umccr/data-portal-client/assets/160200168/4c0c5b9d-5380-4800-82f1-06625d3cd8be)

Refer: https://umccr.slack.com/archives/CP356DDCH/p1719878770753639

**Comment by raylrui** [comment]
@victorskl  should we add .gvcf result for all workflows? 
as I can see, all workflow VCF Results filter with `(r.path.endsWith('vcf') || r.path.endsWith('vcf.gz')`, not include .gvcf.

**Comment by victorskl** [comment]
Yes, please. Thanks Ray.
