### ISSUE TITLE
Implement variant track support

### ISSUE THREAD

**Issue by victorskl** [umccr/data-portal-client#70]
Variant track VCF is avail since `igv.js 2.9.0`. See related:

- https://github.com/igvteam/igv.js/wiki/htsget
- https://github.com/igvteam/igv.js/wiki/Variant-Track
- https://github.com/igvteam/igv.js/wiki/Tracks-2.0
- https://github.com/igvteam/igv.js/issues/1187

**Comment by victorskl** [comment]
There seem to be issue with opening our VCF. Getting gzip compression error at igv.js in console. Need to investigate further.

**Comment by andrewpatto** [comment]
I will put in another PR - there are some other bits of the UI that I will need to add so that variants can be selected (i.e the file list for each patient currently only lists BAMs).
