### ISSUE TITLE
Implement GDS support for IGV.js

### ISSUE THREAD

**Issue by victorskl** [umccr/data-portal-client#82]
**Context:**

- Descoped ticket from #77
- In ☝️IGV desktop app + GDS integration, it is using PreSigned URL for opening bam+bai & vcf+tbi. FYI

**Actions:**

- [x] Implement Open in IGV.js from GDS

**Comment by andrewpatto** [comment]
I would think the way forward with this is to put GDS behind the htsget endpoint.. thoughts?

**Comment by victorskl** [comment]
Sure; wish to explore both possibility:

1. Using PreSignedUL approach (Portal API can `GET /gds/<ID>/presign` or `POST /presign` for GDS file); then [add track](https://github.com/igvteam/igv.js/wiki/Tracks-2.0) using `url` and `indexURL`. This assumes igv.js also support http range request.
2. Also, we should explore find way to add GDS support to Htsget CDK stack; tracking ticket here for that direction -- https://github.com/umccr/infrastructure/issues/196

**Comment by williamputraintan** [comment]
For current implementation in `V2`, it does now support using GDS pre-signed url. Could change this implementation in htsget endpoint when available.

Related PR #153
